name: "Deploy Firebase Functions"
'on':
  push:
    branches:
      - 'master'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/362277105499/locations/global/workloadIdentityPools/github/providers/atelier-api'
          service_account: 'firebase-adminsdk-baddz@atelier-4464b.iam.gserviceaccount.com'
      - run: npm --prefix functions ci
      - run: npm install -g firebase-tools
      - run: firebase deploy
